package org.example.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-23T11:40:33.322+01:00
 * Generated source version: 3.5.1
 *
 */
@WebService(targetNamespace = "http://example.org/", name = "MoT")
@XmlSeeAlso({ObjectFactory.class})
public interface MoT {

    @WebMethod
    @Action(input = "http://example.org/MoT/updateVehicleRequest", output = "http://example.org/MoT/updateVehicleResponse", fault = {@FaultAction(className = BadRequest_Exception.class, value = "http://example.org/MoT/updateVehicle/Fault/BadRequest")})
    @RequestWrapper(localName = "updateVehicle", targetNamespace = "http://example.org/", className = "client.UpdateVehicle")
    @ResponseWrapper(localName = "updateVehicleResponse", targetNamespace = "http://example.org/", className = "client.UpdateVehicleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean updateVehicle(

        @WebParam(name = "arg0", targetNamespace = "")
                RegistrationRequest arg0
    ) throws BadRequest_Exception;

    @WebMethod
    @Action(input = "http://example.org/MoT/registerVehicleRequest", output = "http://example.org/MoT/registerVehicleResponse", fault = {@FaultAction(className = BadRequest_Exception.class, value = "http://example.org/MoT/registerVehicle/Fault/BadRequest")})
    @RequestWrapper(localName = "registerVehicle", targetNamespace = "http://example.org/", className = "client.RegisterVehicle")
    @ResponseWrapper(localName = "registerVehicleResponse", targetNamespace = "http://example.org/", className = "client.RegisterVehicleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean registerVehicle(

        @WebParam(name = "arg0", targetNamespace = "")
                RegistrationRequest arg0
    ) throws BadRequest_Exception;
}
