
package org.example.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-23T11:40:33.238+01:00
 * Generated source version: 3.5.1
 *
 */
public final class MoT_MoTImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://example.org/", "MoTImplService");

    private MoT_MoTImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MoTImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        MoTImplService ss = new MoTImplService(wsdlURL, SERVICE_NAME);
        MoT port = ss.getMoTImplPort();

        {
        System.out.println("Invoking updateVehicle...");
        RegistrationRequest _updateVehicle_arg0 = null;
        try {
            boolean _updateVehicle__return = port.updateVehicle(_updateVehicle_arg0);
            System.out.println("updateVehicle.result=" + _updateVehicle__return);

        } catch (BadRequest_Exception e) {
            System.out.println("Expected exception: BadRequest has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking registerVehicle...");
        RegistrationRequest _registerVehicle_arg0 = null;
        try {
            boolean _registerVehicle__return = port.registerVehicle(_registerVehicle_arg0);
            System.out.println("registerVehicle.result=" + _registerVehicle__return);

        } catch (BadRequest_Exception e) {
            System.out.println("Expected exception: BadRequest has occurred.");
            System.out.println(e.toString());
        }

            }

        System.exit(0);
    }

}
