package org.example.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-23T11:40:33.330+01:00
 * Generated source version: 3.5.1
 *
 */
@WebServiceClient(name = "MoTImplService",
                  wsdlLocation = "file:/C:/Git/NSWI145_Web_Services/05-cxf/MoTClient/src/client/registration.wsdl",
                  targetNamespace = "http://example.org/")
public class MoTImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://example.org/", "MoTImplService");
    public final static QName MoTImplPort = new QName("http://example.org/", "MoTImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Git/NSWI145_Web_Services/05-cxf/MoTClient/src/client/registration.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MoTImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Git/NSWI145_Web_Services/05-cxf/MoTClient/src/client/registration.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MoTImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MoTImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MoTImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public MoTImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MoTImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MoTImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns MoT
     */
    @WebEndpoint(name = "MoTImplPort")
    public MoT getMoTImplPort() {
        return super.getPort(MoTImplPort, MoT.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MoT
     */
    @WebEndpoint(name = "MoTImplPort")
    public MoT getMoTImplPort(WebServiceFeature... features) {
        return super.getPort(MoTImplPort, MoT.class, features);
    }

}
