
package org.example;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.5.1
 * 2022-03-23T11:16:19.141+01:00
 * Generated source version: 3.5.1
 *
 */

public class MoTServer {

    protected MoTServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new MoTImpl();
        String address = "http://localhost:9090/MoTPort";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new MoTServer();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}

